spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 117546400267-uvopeqam0le84p72cb13bh34kdg01c5f.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
        provider:
          google:
            issuer-uri: https://accounts.google.com